version: '3'

services:
  web:
    build: .
    container_name: niatakso_web2
    ports:
      - "8006:8006"
    environment:
      - DB_TYPE=postgresql
      - POSTGRES_HOST=niatakso_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fido&espero&amo
      - POSTGRES_DB=nt_p1
      - DEBUG=True
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8006 --reload
    networks:
      - niatakso_network

networks:
  niatakso_network:
    external: true